name: pull-request
on: 
  pull_request_target

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{github.event.pull_request.head.repo.full_name == 'DuckDuckggo96/upstream-action-check'}}
    steps: 
      - run: echo  ${{github.event.pull_request.head.repo.full_name}} ${{github.event.pull_request.head.repo.full_name}} ${{github.event.pull_request.head.ref}}
 
