name: pull-request
on: 
  pull_request
    branches:
      - develop

jobs:
  integrate:
    runs-on: ubuntu-latest
    environment:
      name: development

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
