name: pull-request
on: 
  pull_request_target

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo  ${{github.ref}} ${{github.repository.name}}  ${{github.event.pull_request.head.repo.full_name}}
