name: pull-request
env:
  JAEYONG: 'jaeyoung0509/upstream-action-check'
  AB: 'DuckDuckggo96/upstream-action-check'
on: 
  pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{github.event.pull_request.head.repo.full_name  == ${{env.JAEYOUNG}} || ${{env.AB}} }} && ${{github.event.pull_request.head.ref == 'main'}}
    steps: 
      - run: echo  ${{github.event.pull_request.head.repo.full_name}} ${{github.event.pull_request.head.repo.full_name}} ${{github.event.pull_request.head.ref}}
 
