name: pull-request
on: 
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/remotes/upstream/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm test
