name: pull-request
on: 
  pull_request

jobs:
  test:
    if: github.repository.name == 'upstream-action-check'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
