name: pull-request
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - 'DuckDuckggo96/**'
      - 'jaeyoung0509/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
