name: pull-request

on: 
  pull_request:
    branches:
      - 'remotes/upstream/main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
         - run: echo  ${{github.event.pull_request.head.repo.full_name}} ${{github.event.pull_request.head.repo.full_name}} ${{github.event.pull_request.head.ref}}
 
