name: pull-request
on: 
  pull_request_target

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - run: echo  ${{github.ref}} ${{github.repository.name}} 
