name: pull-request
on: 
  pull_request
    branches:
      - DuckDuckggo96:main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm test
